CREATE TABLE IF NOT EXISTS topic(
  created TEXT DEFAULT (datetime('now')) NOT NULL,
  text VARCHAR(1000) NOT NULL
);


CREATE TABLE IF NOT EXISTS poll(
  message_id INTEGER NOT NULL,
  casted INTEGER NOT NULL
);
