---

- name: nginx reload
  shell: "nginx -t && nginx -s reload"
  become: true

- name: supervisor reload
  shell: "supervisorctl reread && supervisorctl update"
  become: true

- name: restart app
  shell: "supervisorctl restart {{ app_alias }}"
  become: true
